sudo: required
services:
  - docker

before_install:
  - docker build -t samsonahk/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run samsonahk/react-test npm test -- --coverage

after_success:
  - docker build -t samsonahk/docker-complex-client ./client
  - docker build -t samsonahk/docker-complex-nginx ./nginx
  - docker build -t samsonahk/docker-complex-server ./server
  - docker build -t samsonahk/docker-complex-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push samsonahk/docker-complex-client
  - docker push samsonahk/docker-complex-nginx
  - docker push samsonahk/docker-complex-server
  - docker push samsonahk/docker-complex-worker
  
